### ISSUE TITLE
I am getting following errors: Any help to resolve the issue?

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1142]
`INFO     GetInfoVolumes [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:51] 08-31 17:53:00 

Start task 'GetInfoVolumes'

INFO     GetInfoVolumes [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/storage/cinder_storage.py:259] 08-31 17:53:00 

Filtered volumes: c81a9e64-a25b-41a8-a086-f5584334591e

ERROR    GetInfoVolumes [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:60] 08-31 17:53:00 

GetInfoVolumes TASK FAILED: display_name

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 73, in process_chain
    self.run_task(task)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 65, in run_task
    self.map_func_task[task](task)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 100, in task_run
    task(namespace=self.namespace)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/task.py", line 96, in __call__
    result = self.run(**namespace.vars)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/actions/block_storage/get_info_volumes.py", line 29, in run
    volumes = storage.read_info(**self.search_opts)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/storage/cinder_storage.py", line 104, in read_info
    return self._read_info_volumes(**kwargs)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/storage/cinder_storage.py", line 120, in _read_info_volumes
    volume = self.convert_volume(vol)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/storage/cinder_storage.py", line 436, in convert_volume
    'display_name': vol.display_name,

  File "/usr/local/lib/python2.7/dist-packages/cinderclient/openstack/common/apiclient/base.py", line 463, in __getattr__
    raise AttributeError(k)

AttributeError: display_name

INFO     GetInfoVolumes [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:83] 08-31 17:53:00 

Failed processing CHAIN MIGRATION

INFO     GetInfoVolumes [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:70] 08-31 17:53:00 

Processing CHAIN ROLLBACK

INFO     ImageRollback [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:51] 08-31 17:53:00 

Start task 'ImageRollback'

DEBUG    ImageRollback [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/image/glance_image.py:417] 08-31 17:53:01 

Image 'cirros-0.3.4' status is active.

DEBUG    ImageRollback [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/image/glance_image.py:439] 08-31 17:53:01 

Find image with ID f744cb21-f8b6-4a14-924b-7d2f470793d4(cirros-0.3.4)

DEBUG    ImageRollback [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/image/glance_image.py:417] 08-31 17:53:01 

Image 'cirros-0.3.4-x86_64' status is active.

DEBUG    ImageRollback [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/image/glance_image.py:439] 08-31 17:53:01 

Find image with ID a6fc4f3c-6436-4766-b942-ce1c34c6660b(cirros-0.3.4-x86_64)

INFO     ImageRollback [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/image/glance_image.py:405] 08-31 17:53:01 

Read images: cirros-0.3.4-x86_64 (a6fc4f3c-6436-4766-b942-ce1c34c6660b), cirros-0.3.4 (f744cb21-f8b6-4a14-924b-7d2f470793d4)

INFO     ImageRollback [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:55] 08-31 17:53:02 

End task 'ImageRollback'

INFO     <NoTask> [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:86] 08-31 17:53:02 

Succesfully finished CHAIN ROLLBACK

ERROR    <NoTask> [/usr/local/lib/python2.7/dist-packages/cliff/app.py:349] 08-31 17:53:02 

Migration failed with exit code 3

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/base.py", line 37, in run
    return super(ConfigMixin, self).run(parsed_args)

  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 55, in run
    self.take_action(parsed_args)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/v1/commands.py", line 67, in take_action
    code=status_error))

RuntimeError: Migration failed with exit code 3

Traceback (most recent call last):

  File "/usr/local/bin/cloudferry", line 10, in <module>
    sys.exit(main())

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/shell.py", line 74, in main
    return CloudFerryApp().run(argv)

  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 226, in run
    result = self.run_subcommand(remainder)

  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/base.py", line 37, in run
    return super(ConfigMixin, self).run(parsed_args)

  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 55, in run
    self.take_action(parsed_args)

  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/v1/commands.py", line 67, in take_action
    code=status_error))

RuntimeError: Migration failed with exit code 3
`
Here is my **"configuration.ini"** file, please suggest me what changes I need to make to resolve this:

[configuration.ini.txt](https://github.com/MirantisWorkloadMobility/CloudFerry/files/447220/configuration.ini.txt)

@antonf @SVilgelm @roman-verchikov @plomakin @ntymtsiv @miarmak @openstackmigration @vladiskuz @sk4lf @MirantisWorkloadMobility

**Comment by roman-verchikov** [comment]
That's because your cinder service uses v2 APIs, which are not supported, only cinder v1 is supported.

**Comment by zenpwning** [comment]
@roman-verchikov  Does running "$ cloudferry migrate2 .." i.e, migration version2 of cloudferry can be of any use?

**Comment by SVilgelm** [comment]
no, it is still under development.

**Comment by zenpwning** [comment]
@SVilgelm If I create Cinder Version1 API entity, will it work?

**Comment by zenpwning** [comment]
I've both versions of Cinder API endpoints version 1 & 2, in both source & destination clouds, still facing this issue.

**Comment by roman-verchikov** [comment]
This means you still use cinder v2 APIs
