### ISSUE TITLE
Unable to figure out what the error is pointing for, failing at CheckNetworks stage

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1151]
**CloudFerry Version: 1.54.0** **Under debug mode:**

DEBUG    CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:760] 09-15 12:42:55 Getting info about network 'net04' (f1613299-6274-4766-99a7-9a5453b26a79):
{'admin_state_up': True,
 'id': u'f1613299-6274-4766-99a7-9a5453b26a79',
 'meta': {},
 'name': u'net04',
 'provider:network_type': u'gre',
 'provider:physical_network': None,
 'provider:segmentation_id': 2,
 'res_hash': -6289068945172510578,
 'router:external': False,
 'shared': False,
 'subnets': [{'allocation_pools': [{u'end': u'192.168.111.254',
                                    u'start': u'192.168.111.2'}],
              'cidr': '192.168.111.0/24',
              'dns_nameservers': [u'8.8.4.4', u'8.8.8.8'],
              'enable_dhcp': True,
              'external': False,
              'gateway_ip': u'192.168.111.1',
              'id': u'4bae3809-e571-454b-bc57-eeb1e3a78d98',
              'ip_version': 4,
              'meta': {},
              'name': u'net04__subnet',
              'network_id': u'f1613299-6274-4766-99a7-9a5453b26a79',
              'network_name': u'net04',
              'res_hash': 4431319218708915111,
              'tenant_name': u'admin'}],
 'subnets_hash': set([4431319218708915111]),
 'tenant_id': u'0f944213e3334934ba50cfc80bacc28c',
 'tenant_name': u'admin'}
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:763] 09-15 12:42:55 Done.
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:778] 09-15 12:42:55 Get subnets...
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:786] 09-15 12:42:55 Done
DEBUG    CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:88] 09-15 12:42:55 List of detached ports: []
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:828] 09-15 12:42:55 Get routers
DEBUG    CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:801] 09-15 12:42:56 Finding all ports connected to router 'router04'
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:834] 09-15 12:42:56 Get floatingips...
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:843] 09-15 12:42:56 Done
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py:851] 09-15 12:42:56 Getting security groups and rules...

**WARNING  CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/identity/keystone.py:833] 09-15 12:25:39 Object "tenant" with name "service" not found**
ERROR    CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:60] 09-15 12:25:39 CheckNetworks TASK FAILED: 404 (HTTP 404)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 73, in process_chain
    self.run_task(task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 65, in run_task
    self.map_func_task[task](task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 100, in task_run
    task(namespace=self.namespace)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/task.py", line 96, in __call__
    result = self.run(**namespace.vars)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_networks.py", line 60, in run
    src_net_info = NetworkInfo(src_net.read_info(tenant_id=tenant_ids),
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py", line 124, in read_info
    'security_groups': self.get_sec_gr_and_rules(tenant_id),
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/network/neutron.py", line 854, in get_sec_gr_and_rules
    self.identity_client.get_tenant_id_by_name(service_tenant_name)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/identity/keystone.py", line 290, in get_tenant_id_by_name
    return self.get_tenant_by_name(name).id
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/identity/keystone.py", line 280, in get_tenant_by_name
    'tenant', self.keystone_client.tenants.list(), name)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/identity/keystone.py", line 841, in find_by_name
    404, object_name + ' ' + name + ' not found!')
NotFound: 404 (HTTP 404)
INFO     CheckNetworks [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:83] 09-15 12:25:39 Failed processing CHAIN PREPARATION
ERROR    CheckNetworks [/usr/local/lib/python2.7/dist-packages/cliff/app.py:349] 09-15 12:25:39 Migration failed with exit code 1

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/base.py", line 37, in run
    return super(ConfigMixin, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 55, in run
    self.take_action(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/v1/commands.py", line 67, in take_action
    code=status_error))
RuntimeError: Migration failed with exit code 1
Traceback (most recent call last):
  File "/usr/local/bin/cloudferry", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/shell.py", line 74, in main
    return CloudFerryApp().run(argv)
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 226, in run
    result = self.run_subcommand(remainder)
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/base.py", line 37, in run
    return super(ConfigMixin, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 55, in run
    self.take_action(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/cli/v1/commands.py", line 67, in take_action
    code=status_error))
RuntimeError: Migration failed with exit code 1
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

By the way in the above pasted log under warning line: it show **tenant with "service" name not found**, just because of this I tried changing my tenant name to "service" which actually is "services", after doing the change now I get the warning **tenant with "services" name not found** it's happening vice versa.

@roman-verchikov @SVilgelm @MirantisWorkloadMobility @openstackmigration #

**Comment by roman-verchikov** [comment]
I suppose your config is invalid, `service_tenant` option must be defined in both `[src]` and `[dst]` sections.
