### ISSUE TITLE
Installation failure of Cloudferry using pip gives following error.The python requirements mentioned in CloudFerry Requiremts.txt are not sufficient enough

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1159]
**pip install git+git://github.com/MirantisWorkloadMobility/CloudFerry.git**

as I try the installation of cloudferry using pip on Ubuntu 14.04 machine I get the following error, clearly the python requirements mentioned in [CloudFerry Requiremts.txt](https://github.com/MirantisWorkloadMobility/CloudFerry/blob/master/requirements.txt) are not sufficient enough for installation of cloudferry.

```
Downloading/unpacking git+git://github.com/MirantisWorkloadMobility/CloudFerry.git

  Cloning git://github.com/MirantisWorkloadMobility/CloudFerry.git to /tmp/pip-rlOEeF-build

  Running setup.py (path:/tmp/pip-rlOEeF-build/setup.py) egg_info for package from git+git://github.com/MirantisWorkloadMobility/CloudFerry.git

    warning: no files found matching '*' under directory 'setuptools/_vendor'
    
    Installed /tmp/pip-rlOEeF-build/setuptools-28.0.0-py2.7.egg

    Searching for pbr>=1.9

    Reading https://pypi.python.org/simple/pbr/

    Best match: pbr 1.10.0

    Downloading https://pypi.python.org/packages/c3/2c/63275fab26a0fd8cadafca71a3623e4d0f0ee8ed7124a5bb128853d178a7/pbr-1.10.0.tar.gz#md5=8e4968c587268f030e38329feb9c8f17
    Processing pbr-1.10.0.tar.gz

    Writing /tmp/easy_install-FTMKuZ/pbr-1.10.0/setup.cfg
    Running pbr-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-FTMKuZ/pbr-1.10.0/egg-dist-tmp-k8sfaB
    
    Installed /tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg
    [pbr] Generating ChangeLog

    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg/pbr/util.py", line 264, in cfg_to_args
        wrap_commands(kwargs)
      File "/tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg/pbr/util.py", line 573, in wrap_commands
        cmdclass = ep.load(False)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
   
 ImportError: No module named upload
    error in setup command: Error parsing /tmp/pip-rlOEeF-build/setup.cfg: ImportError: No module named upload
    Complete output from command python setup.py egg_info:
    warning: no files found matching '*' under directory 'setuptools/_vendor'



Installed /tmp/pip-rlOEeF-build/setuptools-28.0.0-py2.7.egg

Searching for pbr>=1.9

Reading https://pypi.python.org/simple/pbr/

Best match: pbr 1.10.0

Downloading https://pypi.python.org/packages/c3/2c/63275fab26a0fd8cadafca71a3623e4d0f0ee8ed7124a5bb128853d178a7/pbr-1.10.0.tar.gz#md5=8e4968c587268f030e38329feb9c8f17

Processing pbr-1.10.0.tar.gz

Writing /tmp/easy_install-FTMKuZ/pbr-1.10.0/setup.cfg

Running pbr-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-FTMKuZ/pbr-1.10.0/egg-dist-tmp-k8sfaB



Installed /tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg

[pbr] Generating ChangeLog

ERROR:root:Error parsing

Traceback (most recent call last):

  File "/tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr

    attrs = util.cfg_to_args(path, dist.script_args)

  File "/tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg/pbr/util.py", line 264, in cfg_to_args

    wrap_commands(kwargs)

  File "/tmp/pip-rlOEeF-build/pbr-1.10.0-py2.7.egg/pbr/util.py", line 573, in wrap_commands

    cmdclass = ep.load(False)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load

    entry = __import__(self.module_name, globals(),globals(), ['__name__'])

ImportError: No module named upload

error in setup command: Error parsing /tmp/pip-rlOEeF-build/setup.cfg: ImportError: No module named upload

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-rlOEeF-build
Storing debug log for failure in /root/.pip/pip.log

```

@roman-verchikov @SVilgelm @MirantisWorkloadMobility @openstackmigration

**Comment by roman-verchikov** [comment]
This works just fine on my machine. Make sure you have the latest version of pip installed, readme suggests using pip==8.1.2

**Comment by SVilgelm** [comment]
```
  checking for gcc... no
  checking for cc... no
  checking for cl.exe... no
  configure: error: in `/tmp/pip-build-gfwDAa/pycrypto':
 configure: error: no acceptable C compiler found in $PATH
```
`apt-get install gcc`

**Comment by zenpwning** [comment]
gcc is present in my system. The latest errors I get are here: [Link](http://pastebin.com/6xAWHnnS)

@roman-verchikov @SVilgelm @MirantisWorkloadMobility @openstackmigration

**Comment by SVilgelm** [comment]
@zenpwning Are you kidding us? You have the logs with all needed information.
http://lmgtfy.com/?q=+fatal+error%3A+openssl%2Fopensslv.h%3A+No+such+file+or+directory

**Comment by zenpwning** [comment]
**I can install cloudferry, I've got a way to do that** but my **sole point is to show that**, if someone tries the installation of cloudferry on fresh ubuntu 14.04 machine, the CF installation is not going to be smooth, they will have to go through all this stuff.
